---
# Default variables for CF Deployment Role

# Default environment configuration (can be overridden by environment configs)
target_environment: dev
cf_environment: "{{ target_environment | default('dev') }}"
cf_namespace: "cf-{{ target_environment | default('dev') }}"
cf_release_name: "cf-microservices-{{ target_environment | default('dev') }}"

# Helm chart configuration
helm_chart_path: "{{ playbook_dir }}/../helm-charts/cf-microservices"
values_file: "{{ playbook_dir }}/../environments/{{ cf_environment }}/deployment-values.yaml"

# Service deployment flags
deploy_naming_server_only: false
deploy_api_gateway_only: false
deploy_spring_boot_admin_only: false
deploy_config_service_only: false
deploy_business_services_only: false
deploy_frontend_only: false

# Individual business service deployment flags
deploy_excel_service_only: false
deploy_bench_profile_only: false
deploy_daily_submissions_only: false
deploy_interviews_only: false
deploy_placements_only: false

# Deployment timeouts (in seconds)
helm_timeout: 600
deployment_wait_timeout: 600

# Verification settings
verify_deployment: true
show_deployment_status: true

# ECR Token Management Configuration
ecr_token_config:
  deployment_name: "ecr-credentials-sync"
  service_account_name: "ecr-credentials-sync"
  rbac_role_name: "ecr-secret-manager"
  rbac_binding_name: "ecr-credentials-sync-binding"
  ecr_registry: "818140567777.dkr.ecr.us-east-1.amazonaws.com"
  aws_region: "us-east-1"
  iam_role_arn: "arn:aws:iam::606639739464:role/ROSAECRAssumeRole"
  secret_name: "ecr-secret"
  base_image: "your-registry/base-image:latest"
  app_version: "1.0"
  timezone: "Asia/Kolkata"
  refresh_interval_hours: 6

# Harness Delegate Configuration
harness_delegate_enabled: true
harness_delegate_namespace: "harness-delegate-ng"
harness_delegate_name: "rosa-harness-delegate"
harness_delegate_sa_name: "harness-delegate"

# Harness Account Configuration
harness_account_id: "B-j8Q1a6Rgm9N6et6GQ6fA"
harness_org_id: "default"
harness_project_id: "cfmonitor"
harness_api_key: "sat.B-j8Q1a6Rgm9N6et6GQ6fA.689dee2655412f3813453e16.uRO6BOdkE29hEa3BrcB4"

# Harness Delegate Token - From Harness UI
harness_delegate_token: "MGMyZmQzYjRjMjQzMmU2YTM0Njc4ODFhNWZhMWI4ODk="

# Harness Endpoints
harness_manager_endpoint: "https://app.harness.io"
harness_log_streaming_endpoint: "https://app.harness.io/log-service/"

# Delegate Configuration
# Use ECR image to avoid internet connectivity issues
harness_delegate_use_fallback_image: false
harness_delegate_ecr_image: "818140567777.dkr.ecr.us-east-1.amazonaws.com/harness-delegate:latest"
harness_delegate_image: "{{ harness_delegate_ecr_image }}"
harness_delegate_replicas: 1
harness_delegate_tags: "rosa,cf-monitor,openshift,{{ target_environment }}"
harness_delegate_description: "ROSA Cluster Delegate for {{ target_environment }} environment"

# Delegate Resource Limits
harness_delegate_memory_limit: "2Gi"
harness_delegate_cpu_limit: "1"
harness_delegate_memory_request: "1Gi"
harness_delegate_cpu_request: "0.5"

# ECR token management control flags
deploy_ecr_token_management: false
ecr_token_management_enabled: "{{ deploy_ecr_token_management | default(false) }}"

