image:
  repository: spring-boot-admin
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

deployment:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

global:
  namespace: cf-dev
  registry: 818140567777.dkr.ecr.us-east-1.amazonaws.com/consultingfirm
  imagePullSecrets:
    - name: regcred
