---
# Simple playbook to deploy Harness delegate directly

- name: Deploy Harness Delegate
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    harness_delegate_namespace: "harness-delegate-ng"
    harness_delegate_name: "rosa-harness-delegate-dev"
    harness_delegate_sa_name: "harness-delegate"
    harness_account_id: "B-j8Q1a6Rgm9N6et6GQ6fA"
    harness_delegate_token: "MGMyZmQzYjRjMjQzMmU2YTM0Njc4ODFhNWZhMWI4ODk="
    harness_manager_endpoint: "https://app.harness.io"
    harness_delegate_image: "818140567777.dkr.ecr.us-east-1.amazonaws.com/harness-delegate:latest"
    harness_delegate_use_fallback_image: false
    harness_delegate_replicas: 1

  tasks:
    - name: Deploy delegate
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ harness_delegate_name }}"
            namespace: "{{ harness_delegate_namespace }}"
            labels:
              app: harness-delegate
          spec:
            replicas: "{{ harness_delegate_replicas }}"
            selector:
              matchLabels:
                app: harness-delegate
            template:
              metadata:
                labels:
                  app: harness-delegate
              spec:
                serviceAccountName: "{{ harness_delegate_sa_name }}"
                imagePullSecrets:
                - name: ecr-secret
                containers:
                - name: delegate
                  image: "{{ harness_delegate_image }}"
                  imagePullPolicy: IfNotPresent
                  env:
                  - name: ACCOUNT_ID
                    value: "{{ harness_account_id }}"
                  - name: DELEGATE_TOKEN
                    value: "{{ harness_delegate_token }}"
                  - name: MANAGER_HOST_AND_PORT
                    value: "{{ harness_manager_endpoint }}"
                  - name: DELEGATE_NAME
                    value: "{{ harness_delegate_name }}"
                  resources:
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
                    requests:
                      memory: "256Mi"
                      cpu: "100m"
        state: present
