---
# Harness Platform Configuration
harness_base_url: "https://app.harness.io"
harness_project_id: "default"

# AWS Configuration
aws_account_id: "818140567777"
ecr_region: "us-east-1"
ecr_registry_url: "{{ aws_account_id }}.dkr.ecr.{{ ecr_region }}.amazonaws.com"

# Delegate Configuration
delegate_name: "harness-{{ rosa_cluster_name | default('dgdev') }}"
delegate_namespace: "harness-delegate-ng"
delegate_replicas: 1
delegate_cpu_request: "250m"
delegate_memory_request: "1Gi"
delegate_cpu_limit: "500m"
delegate_memory_limit: "2Gi"
delegate_jvm_memory: "2048M"
use_ecr_delegate_image: false  # Set to true to use ECR image, false for Docker Hub
delegate_image_tag: "25.08.86503"   # Use newer image version like working delegate

# Git Repository Configuration
cf_monitor_repo_url: "https://github.com/svktekninjas/cf-monitor.git"
cf_deploy_repo_url: "https://github.com/svktekninjas/cf-deploy.git"
git_branch: "main"

# Helm Chart Configuration - Fixed paths
cf_monitor_helm_path: "helm/cf-monitor"
cf_deploy_helm_path: "helm/cf-deploy"
helm_version: "V3"

# ECR Image Configuration - Standardized naming
cf_monitor_image_path: "consultingfirm/cf-monitor"
cf_deploy_image_path: "consultingfirm/cf-deploy"
harness_delegate_image_path: "harness-delegate"

# Kubernetes Configuration
workload_namespace: "cf-workloads"
cluster_permission_type: "CLUSTER_ADMIN"
k8s_permission_type: "CLUSTER_ADMIN"

# Environment Configuration
environments:
  - name: "development"
    identifier: "development"
    type: "PreProduction"
    description: "Development environment for CF workloads"
  - name: "staging"
    identifier: "staging"
    type: "PreProduction"
    description: "Staging environment for CF workloads"
  - name: "production"
    identifier: "production"
    type: "Production"
    description: "Production environment for CF workloads"

# Pipeline Configuration
pipeline_timeout: "10m"
health_check_timeout: "5m"
rollback_timeout: "5m"

# Trigger Configuration
git_trigger_events:
  - "Closed"
auto_abort_previous_executions: false

# Connector Configuration
connector_validation_timeout: 300
delegate_selector_timeout: 600

# Security Configuration
secret_scope: "PROJECT"
secret_type: "SecretText"

# Monitoring Configuration
enable_monitoring: true
enable_notifications: true
notification_channels:
  - email
  - slack

# Deployment Strategy
deployment_strategy: "rolling"
max_unavailable: "25%"
max_surge: "25%"

# Resource Limits
default_cpu_request: "100m"
default_memory_request: "128Mi"
default_cpu_limit: "500m"
default_memory_limit: "512Mi"
