---
# defaults file for rosa-cli role
rosa_cli_version: "latest"
rosa_cli_download_url: "https://mirror.openshift.com/pub/openshift-v4/clients/rosa/latest/rosa-linux.tar.gz"
rosa_cli_install_path: "/usr/local/bin"
rosa_cli_binary_name: "rosa"
rosa_auth_token: ""
target_environment: "dev"
terraform_env_path: "/Users/swaroop/Documents/FullStack-SRE/ConsultingFirm_infra/ROSA/terraform/environments"