---
# Internal role variables - not meant to be overridden
harness_api_endpoints:
  delegates: "/gateway/ng/api/download-delegates/docker"
  connectors: "/gateway/ng/api/connectors"
  environments: "/gateway/ng/api/environmentsV2"
  infrastructures: "/gateway/ng/api/infrastructures"
  services: "/gateway/ng/api/servicesV2"
  pipelines: "/gateway/pipeline/api/pipelines/v2"
  triggers: "/gateway/pipeline/api/triggers"
  secrets: "/gateway/ng/api/v2/secrets"

# Connector types mapping
connector_types:
  git: "Github"
  ecr: "DockerRegistry"
  k8s: "K8sCluster"
  aws: "Aws"

# Service definition types
service_types:
  kubernetes: "Kubernetes"
  helm: "HelmChart"

# Deployment types
deployment_types:
  kubernetes: "Kubernetes"
  helm: "Helm"

# Trigger types
trigger_types:
  webhook: "Webhook"
  github: "Github"
  pullrequest: "PullRequest"

# Pipeline stage types
stage_types:
  deployment: "Deployment"
  approval: "Approval"
  custom: "Custom"

# Step types
step_types:
  helm_deploy: "HelmDeploy"
  helm_rollback: "HelmRollback"
  k8s_deploy: "K8sRollingDeploy"
  k8s_bluegreen: "K8sBlueGreenDeploy"
  health_check: "Http"

# Authentication types
auth_types:
  username_token: "UsernameToken"
  username_password: "UsernamePassword"
  inherit_delegate: "InheritFromDelegate"
  service_account: "ServiceAccount"

# Git fetch types
git_fetch_types:
  branch: "Branch"
  commit: "Commit"
  tag: "Tag"

# Artifact types
artifact_types:
  docker: "DockerRegistry"
  ecr: "Ecr"
  gcr: "Gcr"

# Environment types
environment_types:
  production: "Production"
  preproduction: "PreProduction"

# Infrastructure types
infrastructure_types:
  k8s_direct: "KubernetesDirect"
  k8s_gcp: "KubernetesGcp"
  k8s_aws: "KubernetesAws"
