apiVersion: v1
kind: Service
metadata:
  name: apigateway-app
  namespace: {{ .Values.global.namespace }}
  labels:
    app: apigateway-app
    version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: apigateway-app