# Default variables for monitoring role
# These defaults reference values from monitoring-variables.yml
---
# Environment Configuration
target_environment: "{{ valid_environments[0] if valid_environments is defined else 'dev' }}"
ansible_env_path: "{{ playbook_dir }}/../environments/{{ target_environment }}"

# Monitoring Basic Configuration
monitoring_namespace: "{{ default_monitoring_config.namespace }}"
enable_monitoring: true
enable_cloudwatch_integration: "{{ enable_cloudwatch_insights | default(true) }}"

# Prometheus Configuration
prometheus_enabled: true
prometheus_namespace: "{{ prometheus_config.namespace if prometheus_config is defined else monitoring_namespace }}"
prometheus_storage_size: "{{ prometheus_config.storage_size if prometheus_config is defined else '10Gi' }}"
prometheus_retention: "{{ prometheus_config.retention_period if prometheus_config is defined else '15d' }}"
prometheus_image: "{{ container_images.prometheus }}"

# Grafana Configuration
grafana_enabled: true
grafana_namespace: "{{ grafana_config.namespace if grafana_config is defined else monitoring_namespace }}"
grafana_admin_user: "{{ grafana_config.admin_user if grafana_config is defined else 'admin' }}"
grafana_admin_password: "{{ grafana_config.admin_password if grafana_config is defined else 'admin123' }}"
grafana_image: "{{ container_images.grafana }}"

# Node Exporter Configuration
node_exporter_enabled: true
node_exporter_namespace: "{{ node_exporter_config.namespace if node_exporter_config is defined else monitoring_namespace }}"
node_exporter_image: "{{ container_images.node_exporter }}"

# CloudWatch Configuration
cloudwatch_log_group: "{{ cloudwatch_log_group if cloudwatch_log_group is defined else '/rosa/cluster/default' }}"
cloudwatch_region: "{{ aws_region | default('us-east-1') }}"
cloudwatch_log_retention: "{{ cloudwatch_log_retention_days if cloudwatch_log_retention_days is defined else 14 }}"

# OpenShift Log Forwarding Configuration
openshift_log_forwarding_enabled: "{{ openshift_log_forwarding.enable_cluster_logging if openshift_log_forwarding is defined else true }}"

# Alerting Configuration
alerting_enabled: "{{ alerting_config.enable_alerts if alerting_config is defined else false }}"
alert_severity: "{{ alerting_config.alert_severity if alerting_config is defined else 'warning' }}"

# Security Configuration
enable_rbac: "{{ default_monitoring_config.enable_rbac }}"
enable_security_context: "{{ default_monitoring_config.enable_security_context }}"
enable_network_policies: "{{ default_monitoring_config.enable_network_policies }}"

# Resource Requirements (defaults to dev)
prometheus_memory_request: "{{ resource_requirements.dev.prometheus.memory_request }}"
prometheus_memory_limit: "{{ resource_requirements.dev.prometheus.memory_limit }}"
prometheus_cpu_request: "{{ resource_requirements.dev.prometheus.cpu_request }}"
prometheus_cpu_limit: "{{ resource_requirements.dev.prometheus.cpu_limit }}"

grafana_memory_request: "{{ resource_requirements.dev.grafana.memory_request }}"
grafana_memory_limit: "{{ resource_requirements.dev.grafana.memory_limit }}"
grafana_cpu_request: "{{ resource_requirements.dev.grafana.cpu_request }}"
grafana_cpu_limit: "{{ resource_requirements.dev.grafana.cpu_limit }}"

# Exposure Configuration
expose_grafana: "{{ grafana_config.expose_route if grafana_config is defined else true }}"
expose_prometheus: true

# Operational Settings
wait_for_monitoring_ready: true
monitoring_ready_timeout: "{{ timeout_values.prometheus_startup }}"
skip_monitoring_validation: false

# Debug and Development Settings
debug_mode: "{{ dev_settings.debug_mode if dev_settings is defined else false }}"
verbose_logging: "{{ dev_settings.verbose_logging if dev_settings is defined else false }}"
