---
# Task 3: Environment setup and .env file updates

- name: "Prompt for environment selection"
  pause:
    prompt: "Please select the environment (dev/test/prod)"
  register: environment_input
  when: target_environment is not defined
  tags: aws

- name: "Set target environment from input"
  set_fact:
    target_environment: "{{ environment_input.user_input }}"
  when: environment_input is defined and environment_input.user_input is defined
  tags: aws

- name: "Validate environment selection"
  fail:
    msg: "Invalid environment selection. Please choose from: dev, test, prod"
  when: target_environment not in ['dev', 'test', 'prod']
  tags: aws

- name: "Set ansible environment path"
  set_fact:
    ansible_env_path: "{{ playbook_dir }}/../environments/{{ target_environment }}"
  tags: aws

- name: "Check if ansible environment directory exists"
  stat:
    path: "{{ ansible_env_path }}"
  register: ansible_env_dir
  tags: aws

- name: "Create ansible environment directory if it doesn't exist"
  file:
    path: "{{ ansible_env_path }}"
    state: directory
    mode: '0755'
  when: not ansible_env_dir.stat.exists
  tags: aws

- name: "Check if .env file exists"
  stat:
    path: "{{ ansible_env_path }}/.env"
  register: env_file_check
  tags: aws

- name: "Create .env file from template"
  template:
    src: env.j2
    dest: "{{ ansible_env_path }}/.env"
    mode: '0644'
  when: not env_file_check.stat.exists
  tags: aws

- name: "Update .env file with AWS profile configuration"
  blockinfile:
    path: "{{ ansible_env_path }}/.env"
    block: |
      # AWS Configuration (Profile-based)
      AWS_PROFILE={{ aws_profile }}
      AWS_DEFAULT_REGION={{ aws_region | default('us-east-1') }}
      AWS_REGION={{ aws_region | default('us-east-1') }}

      # Environment Configuration
      ENVIRONMENT={{ target_environment }}
      TERRAFORM_WORKSPACE={{ target_environment }}
    marker: "# {mark} ANSIBLE MANAGED AWS BLOCK"
    create: yes
  tags: aws

- name: "Set environment variables in current session"
  shell: |
    export AWS_PROFILE={{ aws_profile }}
    export AWS_DEFAULT_REGION={{ aws_region | default('us-east-1') }}
    export AWS_REGION={{ aws_region | default('us-east-1') }}
    export ENVIRONMENT={{ target_environment }}
    export TERRAFORM_WORKSPACE={{ target_environment }}
  tags: aws

- name: "Create environment export script"
  template:
    src: export_env.sh.j2
    dest: "{{ ansible_env_path }}/export_env.sh"
    mode: '0755'
  tags: aws

- name: "Display environment setup completion"
  debug:
    msg: |
      Environment setup completed successfully!

      Configuration:
      - Environment: {{ target_environment }}
      - Ansible environment path: {{ ansible_env_path }}
      - .env file updated: {{ ansible_env_path }}/.env
      - Export script created: {{ ansible_env_path }}/export_env.sh

      To use the environment variables in your shell, run:
      source {{ ansible_env_path }}/export_env.sh
  tags: aws
