---
# Main tasks for cf-harness role
# Supports both CLI and API methods (API recommended for full functionality)

- name: Display role execution information
  debug:
    msg: |
      Setting up Harness for environment: {{ environment }}
      Method: {{ 'Harness CLI' if use_harness_cli | default(false) | bool else 'REST API (Recommended)' }}
  tags:
    - always

# Option 1: Setup using Harness CLI (limited functionality)
- name: Setup Harness CLI
  include_tasks: check_harness_cli.yml
  when: use_harness_cli | default(false) | bool
  tags:
    - cli
    - setup

# Option 2: Setup using REST API (full functionality - recommended)
- name: Validate prerequisites
  include_tasks: validate_prerequisites.yml
  when: validate_prerequisites | default(true) | bool
  tags:
    - validate
    - prerequisites

- name: Setup service accounts with IRSA
  include_tasks: setup_service_accounts.yml
  when: enable_irsa_configuration | default(true) | bool
  tags:
    - serviceaccount
    - irsa
    - rbac

- name: Install Harness Delegate
  include_tasks: install_delegate.yml
  when: enable_delegate_installation | default(true) | bool
  tags:
    - delegate
    - install

# Use API versions for better functionality
- name: Setup Harness connectors via API
  include_tasks: "{{ 'setup_connectors.yml' if use_harness_cli | default(false) | bool else 'setup_connectors_api.yml' }}"
  when: enable_connector_creation | default(true) | bool
  tags:
    - connectors
    - setup
    - api

- name: Apply Harness resources via API
  include_tasks: "{{ 'apply_harness_resources.yml' if use_harness_cli | default(false) | bool else 'apply_harness_resources_api.yml' }}"
  when: enable_service_creation | default(true) | bool
  tags:
    - resources
    - services
    - pipelines
    - api

- name: Validate Harness setup via API
  include_tasks: "{{ 'validate_installation.yml' if use_harness_cli | default(false) | bool else 'validate_installation_api.yml' }}"
  tags:
    - validate
    - test
    - api

- name: Display completion message
  debug:
    msg: |
      Harness setup completed successfully!
      - Delegate: {{ harness_delegate_name }}
      - Namespace: {{ harness_delegate_namespace }}
      - Environment: {{ environment }}
      - Connectors created: AWS ECR, ROSA Cluster, GitHub
  tags:
    - always