---
# Main task orchestration for Harness setup
- name: Validate required variables
  include_tasks: validate.yml
  tags:
    - cf-harness
    - validation
    - always

- name: Create Harness projects
  include_tasks: cf-harness-project.yml
  tags:
    - cf-harness
    - projects
    - setup

- name: Setup secrets in Harness
  include_tasks: secrets.yml
  tags:
    - cf-harness
    - secrets
    - setup

- name: Deploy Harness delegate to ROSA cluster
  include_tasks: delegate.yml
  tags:
    - cf-harness
    - delegate
    - infrastructure

- name: Configure Harness connectors
  include_tasks: connectors.yml
  tags:
    - cf-harness
    - connectors
    - configuration

- name: Setup environments and infrastructure
  include_tasks: environments.yml
  tags:
    - cf-harness
    - environments
    - infrastructure

- name: Create Harness services
  include_tasks: services.yml
  tags:
    - cf-harness
    - services
    - configuration

- name: Create deployment pipelines
  include_tasks: pipelines.yml
  tags:
    - cf-harness
    - pipelines
    - deployment

- name: Configure triggers
  include_tasks: triggers.yml
  tags:
    - cf-harness
    - triggers
    - automation

- name: Verify setup
  include_tasks: verify.yml
  tags:
    - cf-harness
    - verification
    - testing
