---
# Create secrets in both projects
- name: Create GitHub token secret in both projects
  uri:
    url: "{{ harness_base_url }}{{ harness_api_endpoints.secrets }}?accountIdentifier={{ harness_account_id }}&orgIdentifier={{ harness_org_id }}&projectIdentifier={{ item }}"
    method: POST
    headers:
      x-api-key: "{{ harness_api_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      secret:
        type: "{{ secret_type }}"
        name: "github-token"
        identifier: "github_token"
        description: "GitHub personal access token for repository access"
        spec:
          secretManagerIdentifier: "harnessSecretManager"
          valueType: "Inline"
          value: "{{ github_token }}"
        orgIdentifier: "{{ harness_org_id }}"
        projectIdentifier: "{{ item }}"
    status_code: [200, 201, 400]
  loop:
    - cf_monitor
    - cf_app
  register: github_secret_results

- name: Display secrets creation status
  debug:
    msg: "Created GitHub token secret in both cf_monitor and cf_app projects"

# Note: AWS ECR credentials should be managed via IAM roles or delegate credentials
# rather than storing them as secrets in Harness when using KMS