# Main tasks file for routes role - orchestrates all route creation tasks
---
- name: "Load routes variables"
  include_vars: routes-variables.yml
  tags:
    - routes

- name: "Load environment-specific routes configuration"
  include_vars: "{{ ansible_env_path }}/routes-config.yml"
  tags:
    - routes

- name: "Start ROSA Cluster Routes Setup for {{ target_environment }} environment"
  debug:
    msg: "🌐 Starting ROSA Cluster Routes Setup for {{ target_environment }} environment"
  tags:
    - routes

# CF-Dev Namespace Routes
- name: Include API Gateway route creation
  include_tasks: create_apigateway_route.yml
  when: routes_config.apigateway.enabled | default(true)
  tags:
    - routes
    - routes-apigateway
    - apigateway
    - cf-dev

- name: Include Frontend Custom route creation
  include_tasks: create_frontend_custom_route.yml
  when: routes_config.frontend_custom.enabled | default(true)
  tags:
    - routes
    - routes-frontend-custom
    - frontend
    - cf-dev

- name: Include Frontend Service route creation
  include_tasks: create_frontend_service_route.yml
  when: routes_config.frontend_service.enabled | default(true)
  tags:
    - routes
    - routes-frontend-service
    - frontend
    - cf-dev

# Monitoring Namespace Routes
- name: Include Grafana route creation
  include_tasks: create_grafana_route.yml
  when: routes_config.grafana.enabled | default(true)
  tags:
    - routes
    - routes-grafana
    - grafana
    - monitoring

- name: Include Prometheus route creation
  include_tasks: create_prometheus_route.yml
  when: routes_config.prometheus.enabled | default(true)
  tags:
    - routes
    - routes-prometheus
    - prometheus
    - monitoring

# Route Validation
- name: Include CF-Dev routes validation
  include_tasks: validate_cf_dev_routes.yml
  when: validate_routes_enabled | default(true)
  tags:
    - routes
    - routes-validate
    - cf-dev
    - validation

- name: Include monitoring routes validation
  include_tasks: validate_routes.yml
  when: validate_routes_enabled | default(true)
  tags:
    - routes
    - routes-validate
    - monitoring
    - validation

- name: "Complete ROSA Cluster Routes Setup for {{ target_environment }} environment"
  debug:
    msg: "✅ ROSA Cluster Routes Setup completed successfully for {{ target_environment }} environment!"
  tags:
    - routes
