# Default variables for cluster role
# These defaults reference values from cluster-variables.yml
---
# Environment Configuration
target_environment: "{{ valid_environments[0] }}"  # Defaults to 'dev'
ansible_env_path: "{{ playbook_dir }}/../environments/{{ target_environment }}"

# Cluster Basic Configuration
cluster_name_prefix: "rosa-cluster"
full_cluster_name: "{{ cluster_name_prefix }}-{{ target_environment }}"
cluster_description: "ROSA cluster managed by Ansible"
openshift_version: "{{ supported_openshift_versions[-1] }}"  # Latest supported version

# AWS Configuration
aws_region: "{{ supported_aws_regions[0] }}"  # Defaults to 'us-east-1'
multi_az: false

# STS Configuration
sts_enabled: true
mode: "auto"
operator_roles_prefix_auto: true

# Network Configuration
machine_cidr: "10.0.0.0/16"
service_cidr: "172.30.0.0/16"
pod_cidr: "10.128.0.0/14"
host_prefix: 23

# Compute Configuration
compute_nodes: "{{ minimum_requirements.dev.compute_nodes }}"  # Defaults to dev requirements
compute_machine_type: "{{ supported_compute_machine_types[1] }}"  # Defaults to 'm5n.xlarge'
enable_autoscaling: false
min_replicas: "{{ minimum_requirements.dev.compute_nodes }}"
max_replicas: 4

# Storage Configuration
storage_type: "{{ supported_storage_types[0] }}"  # Defaults to 'gp3'
storage_size: "300"

# Security Configuration
private_cluster: false
privatelink_enabled: false

# Monitoring and Logging
enable_monitoring: true
enable_logging: false

# Cluster Features
enable_fips: false
enable_etcd_encryption: false

# Cluster Access
create_admin_user: true
admin_username: "cluster-admin"

# Operational Settings
wait_for_cluster_ready: true
cluster_ready_timeout: "{{ timeout_values.cluster_creation }}"  # Defaults to 3600 seconds
destroy_cluster_on_completion: false

# Validation Settings
validate_cluster_config: true
validate_prerequisites: true
skip_cluster_validation: false
