image:
  repository: naming-server-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

deployment:
  replicas: 1
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "openshift"
    - name: SERVER_PORT
      value: "8761"
    - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
      value: "false"
    - name: EUREKA_CLIENT_FETCH_REGISTRY
      value: "false"
    - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL
      value: "http://naming-server-new:8761"
    - name: SPRING_BOOT_ADMIN_CLIENT_URL
      value: "http://spring-boot-admin:8082"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "health,info,metrics"
    - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: "always"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

global:
  namespace: cf-dev
  registry: 818140567777.dkr.ecr.us-east-1.amazonaws.com/consultingfirm
  imagePullSecrets:
    - name: ecr-secret