---
# CF Deployment Playbook - Dedicated playbook for microservices deployment
# This playbook handles CF microservices deployment and Harness delegate installation

- name: CF Microservices and Harness Delegate Deployment
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - "../environments/{{ target_environment | default('dev') }}/{{ target_environment | default('dev') }}.yml"
    - "../environments/{{ target_environment | default('dev') }}/cf-deployment.yml"

  pre_tasks:
    - name: Display deployment start
      debug:
        msg:
          - "Starting CF deployment for {{ target_environment | default('dev') }} environment"
          - "Harness delegate enabled: {{ harness_delegate_enabled | default(true) }}"
      tags:
        - always

  roles:
    - role: cf-deployment
      tags:
        - cf-deployment
        - microservices
        - deployment
        - harness-delegate
        - harness

  post_tasks:
    - name: Display deployment completion
      debug:
        msg: "CF deployment completed successfully for {{ target_environment | default('dev') }}"
      tags:
        - always
