---
# ROSA Cluster Cleanup Playbook
# This playbook safely removes a ROSA cluster and all associated resources
# 
# Usage:
#   ansible-playbook playbooks/cleanup_cluster.yml -e "target_environment=dev" -e "aws_profile=sid-KS"
#   ansible-playbook playbooks/cleanup_cluster.yml -e "target_environment=dev" -e "aws_profile=sid-KS" -e "delete_cluster_vpc=true"
#   ansible-playbook playbooks/cleanup_cluster.yml -e "cluster_name=rosa-cluster-dev" -e "aws_profile=sid-KS"
#
# Variables:
#   - target_environment: Environment to clean up (dev/test/prod)
#   - cluster_name: Specific cluster name to delete (optional, overrides environment)
#   - aws_profile: AWS profile to use
#   - delete_cluster_vpc: Whether to delete the VPC (default: false)
#   - aws_region: AWS region (default: us-east-1)

- name: ROSA Cluster Cleanup
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    # Set defaults for all variables to avoid undefined errors
    cluster_cleanup: true
    delete_cluster_vpc: false  # Safety default - don't delete VPC unless explicitly requested
    aws_region: "{{ aws_region | default('us-east-1') }}"
    
    # Handle both cluster_name and target_environment scenarios
    # If target_environment is provided, construct the full name
    # If cluster_name is provided directly, use it
    cluster_name_prefix: "rosa-cluster"  # Default prefix
    ansible_env_path: "{{ playbook_dir }}/../environments/{{ target_environment | default('dev') }}"
    full_cluster_name: "{% if cluster_name is defined %}{{ cluster_name }}{% elif target_environment is defined %}{{ cluster_name_prefix }}-{{ target_environment }}{% else %}rosa-cluster-dev{% endif %}"
    
  pre_tasks:
    - name: Validate required variables
      assert:
        that:
          - aws_profile is defined
          - target_environment is defined or cluster_name is defined
        fail_msg: |
          Missing required variables. Please provide:
          - aws_profile: AWS profile to use
          - target_environment: Environment (dev/test/prod) OR cluster_name: Specific cluster name
          
          Example:
          ansible-playbook playbooks/cleanup_cluster.yml -e "target_environment=dev" -e "aws_profile=sid-KS"
        success_msg: "Variables validated. Proceeding with cleanup."
      tags:
        - always
        
    - name: Load environment configuration if target_environment is provided
      include_vars: "{{ ansible_env_path }}/cluster-config.yml"
      when: target_environment is defined
      ignore_errors: yes  # Don't fail if file doesn't exist
      tags:
        - always

    - name: Display cleanup configuration
      debug:
        msg:
          - "=== ROSA Cluster Cleanup Configuration ==="
          - "Target Environment: {{ target_environment | default('custom') }}"
          - "Cluster Name: {{ full_cluster_name }}"
          - "AWS Profile: {{ aws_profile }}"
          - "AWS Region: {{ aws_region }}"
          - "Delete VPC: {{ delete_cluster_vpc }}"
          - "=========================================="
      tags:
        - always

  tasks:
    - name: Include cluster cleanup tasks directly
      include_role:
        name: cluster
        tasks_from: cluster_cleanup_simple.yml
      tags:
        - cluster-cleanup
        - cleanup

  post_tasks:
    - name: Final cleanup confirmation
      debug:
        msg:
          - "=== Cleanup Complete ==="
          - "All cluster resources have been removed."
          - "Please verify in AWS Console that all resources are deleted."
          - "========================"
      tags:
        - always