- name: ROSA Infrastructure Setup
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - "../environments/{{ target_environment | default('dev') }}/{{ target_environment | default('dev') }}.yml"

  pre_tasks:
    - name: Display playbook start
      debug:
        msg: "Starting ROSA infrastructure setup process for {{ target_environment | default('dev') }} environment"

  roles:
    - role: aws-setup
      tags: ['aws', 'setup']
    - role: rosa-cli
      tags: ['rosa']
    - role: validation
      tags: ['validation', 'pre-checks']
    - role: cluster
      tags: ['cluster', 'rosa-cluster']
#    - role: monitoring
#      tags: ['monitoring', 'observability']
#    - role: routes
#      tags: ['routes', 'networking', 'ingress']
    - role: cf-db
      tags: ['cf-db', 'database', 'aurora', 'postgresql']
#    - role: cf-deployment
#      tags: ['cf-deployment', 'microservices', 'deployment']

  post_tasks:
    - name: Display playbook completion
      debug:
        msg: "ROSA infrastructure setup completed successfully"
