# Development Environment - ROSA Cluster Configuration
---
# Cluster Basic Configuration
cluster_name_prefix: "rosa-cluster"
cluster_description: "Development ROSA cluster for testing and development workloads"
openshift_version: "4.18.20"

# AWS Configuration
aws_region: "us-east-1"
availability_zones:
  - "us-east-1a"
  - "us-east-1b"
multi_az: false

# STS Configuration
sts_enabled: true
mode: "auto"
operator_roles_prefix_auto: true

# Network Configuration
machine_cidr: "10.0.0.0/16"
service_cidr: "172.30.0.0/16"
pod_cidr: "10.128.0.0/14"
host_prefix: 23

# Compute Configuration
compute_nodes: 2
compute_machine_type: "m5n.xlarge"
enable_autoscaling: true
min_replicas: 2
max_replicas: 4

# Storage Configuration
storage_type: "gp3"
storage_size: "300"

# Security Configuration
private_cluster: false
privatelink_enabled: false
additional_security_groups: []

# Monitoring and Logging
enable_monitoring: true
enable_logging: false

# Cluster Features
enable_fips: false
enable_etcd_encryption: false

# Cluster Access
create_admin_user: true
admin_username: "cluster-admin"

# Backup and Maintenance
disable_workload_monitoring: false
cluster_auto_upgrade: false

# Development specific settings
destroy_cluster_on_completion: false
wait_for_cluster_ready: false
cluster_ready_timeout: 3600  # 1 hour
cluster_creation_timeout_minutes: 3  # 3 minutes for quick checks

# Cost Optimization
enable_spot_instances: false
hibernate_cluster: false

# Resource Tagging Configuration
resource_tags:
  app-dev: "{{ full_cluster_name | default('rosa-cluster-dev') }}"
