# Development Environment Routes Configuration
---
# Environment settings
target_environment: "dev"
environment_name: "Development"

# Routes configuration for dev environment
routes_config:
  monitoring_namespace: "monitoring"
  cf_namespace: "cf-dev"
  
  # API Gateway route configuration
  apigateway:
    hostname: "apigateway-app-cf-dev.apps.o0r9m0f2v7l3b1c.55n4.p1.openshiftapps.com"
    service_name: "apigateway-app"
    target_port: "http"
    route_name: "apigateway-app"
    enabled: true
    
  # Frontend Custom route configuration (probuddy.us domain)
  frontend_custom:
    hostname: "cfdev.probuddy.us"
    service_name: "frontend-service"
    target_port: "http"
    route_name: "frontend-custom"
    enabled: true
    
  # Frontend Service route configuration (OpenShift domain)
  frontend_service:
    hostname: "frontend-service-cf-dev.apps.o0r9m0f2v7l3b1c.55n4.p1.openshiftapps.com"
    service_name: "frontend-service"
    target_port: "http"
    route_name: "frontend-service"
    enabled: true
  
  # Grafana route configuration
  grafana:
    hostname: "grafana-dev.probuddy.us"
    service_name: "grafana"
    target_port: 3000
    route_name: "grafana-route"
    enabled: true
    
  # Prometheus route configuration
  prometheus:
    hostname: "prometheus-dev.probuddy.us"
    service_name: "prometheus"
    target_port: 9090
    route_name: "prometheus-route"
    enabled: true
    
  # TLS configuration
  tls:
    termination: "edge"
    insecure_edge_termination_policy: "Redirect"
    
# Development-specific settings
dev_settings:
  debug_mode: true
  verbose_logging: true
  validation_timeout: 60
  
# Route validation settings for dev
validation_settings:
  enabled: true
  http_timeout: 10
  retry_attempts: 3
  expected_status_codes:
    - 200
    - 301
    - 302
    - 401  # Grafana login page
    
# AWS Profile (inherited from main config)
aws_profile: "{{ aws_profile | default('default') }}"

# Resource settings for dev (minimal)
resource_settings:
  route_timeout: "30s"
  max_connections: 100
  
# Monitoring integration
monitoring_integration:
  enable_route_monitoring: true
  metrics_collection: false  # Disabled for dev to reduce overhead